---
# Include variable definitions
- name: "include variable overrides"
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "vars/{{ ansible_distribution }}.yml"
      - "vars/{{ ansible_os_family }}.yml"
      skip: true
  tags:
    - zip

# Install packages
- name: install zip packages
  package: >
    name="{{ zip_packages }}"
    state="{{ zip_packages_state }}"
  become: yes
  tags:
    - zip
